# Generated by Django 2.0 on 2020-05-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_list', models.IntegerField(default=0)),
                ('job_post', models.IntegerField(default=0)),
                ('Job_received', models.IntegerField(default=0)),
                ('request_post', models.IntegerField(default=0)),
                ('request_received', models.IntegerField(default=0)),
            ],
        ),
    ]
