# Generated by Django 2.0 on 2020-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_list_items', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestPostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_post_text', models.CharField(max_length=100)),
            ],
        ),
    ]
