# Generated by Django 2.0 on 2020-05-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_joblistform_jobpostform_requestpostform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1000)),
                ('job_post_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.JobPostForm')),
            ],
        ),
        migrations.CreateModel(
            name='UserFreelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1000)),
                ('request_post_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.RequestPostForm')),
            ],
        ),
    ]
