# Generated by Django 2.0 on 2020-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_useremployer_userfreelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1000)),
            ],
        ),
    ]
