# Generated by Django 2.0 on 2020-05-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_auto_20200523_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobListForm',
        ),
        migrations.DeleteModel(
            name='UserAFC',
        ),
        migrations.RemoveField(
            model_name='useremployer',
            name='job_post_form',
        ),
        migrations.RemoveField(
            model_name='userfreelancer',
            name='request_post_form',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='JobPostForm',
        ),
        migrations.DeleteModel(
            name='RequestPostForm',
        ),
        migrations.DeleteModel(
            name='UserEmployer',
        ),
        migrations.DeleteModel(
            name='UserFreelancer',
        ),
    ]
